import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import React from "react";
import {
  Navbar,
  NavbarBrand,
  NavbarContent,
  NavbarItem,
  Link,
} from "@nextui-org/react";
const inter = Inter({ subsets: ["latin"] });
import { ThemeSwitcher } from "./components/layout/ThemeSwitcher";
export const metadata: Metadata = {
  title: "Where in the world?",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-veryLightGreyBG dark:bg-veryDarkBlueBG text-veryDarkBlueText dark:text-whiteTXT">
        <Providers>
          <Navbar shouldHideOnScroll className="dark:bg-darkBlueElements">
            <NavbarBrand>
              <Link href="/" className="font-bold text-inherit">Where in the world?</Link>
            </NavbarBrand>
            <NavbarContent className="hidden sm:flex gap-4" justify="center">
              <NavbarItem>
                <Link color="foreground" href="#" className="font-semibold">
                  Designed by Brian Kung'u
                </Link>
              </NavbarItem>
            </NavbarContent>
            <NavbarContent justify="end">
              <NavbarItem>
                <ThemeSwitcher />
              </NavbarItem>
            </NavbarContent>
          </Navbar>

          {children}
        </Providers>
      </body>
    </html>
  );
}
